import poService = require("dataAccessServices/PurchaseOrder.service");
poService; // necessary to cause define function to generated by TypeScript compiler

class PurchaseOrdersController implements IFeatureController {
    public title: string = "Purchase Orders";
    public purchaseOrders: poService.IPurchaseOrderPageable;

    constructor($scope: any, private purchaseOrderService: poService.PurchaseOrdersService) {
        this.purchaseOrders = this.purchaseOrderService.fetchAll(10, 1);
    }
}
angular.module("app").controller("PurchaseOrdersController", PurchaseOrdersController);