import poService = require("dataAccessServices/PurchaseOrder.service");
poService; // necessary to cause define function to generated by TypeScript compiler

interface IRouteServiceFix extends ng.route.IRouteService {
    updateParams(object: any): void;
}

class PurchaseOrdersController implements IFeatureController {
    public title: string = "Purchase Orders";
    public purchaseOrders: poService.IPurchaseOrderPageable;

    constructor(private purchaseOrderService: poService.PurchaseOrdersService, private $route: IRouteServiceFix) {
        this.purchaseOrders = this.purchaseOrderService.fetchAll(10, 1);
    }

    public navigate(idValue: number) {
        this.$route.updateParams({ id: idValue });
    }
}

angular.module("app").controller("PurchaseOrdersController", PurchaseOrdersController);